// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// Admins is the golang structure for table admins.
type Admins internal.Admins

// Fill with you ideas below.