// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// AuthoritiesMenus is the golang structure for table authorities_menus.
type AuthoritiesMenus internal.AuthoritiesMenus

// Fill with you ideas below.