// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// AuthorityMenu is the golang structure for table authority_menu.
type AuthorityMenu internal.AuthorityMenu

// Fill with you ideas below.