// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// Authorities is the golang structure for table authorities.
type Authorities internal.Authorities

// Fill with you ideas below.