// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// BreakpointContinue is the golang structure for table breakpoint_continue.
type BreakpointContinue internal.BreakpointContinue

// Fill with you ideas below.