// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// BreakpointContinueChunks is the golang structure for table breakpoint_continue_chunks.
type BreakpointContinueChunks internal.BreakpointContinueChunks

// Fill with you ideas below.