// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// DataAuthorities is the golang structure for table data_authorities.
type DataAuthorities internal.DataAuthorities

// Fill with you ideas below.