// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// Dictionaries is the golang structure for table dictionaries.
type Dictionaries internal.Dictionaries

// Fill with you ideas below.