// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// DictionaryDetails is the golang structure for table dictionary_details.
type DictionaryDetails internal.DictionaryDetails

// Fill with you ideas below.