// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// Files is the golang structure for table files.
type Files internal.Files

// Fill with you ideas below.