// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// JwtBlacklists is the golang structure for table jwt_blacklists.
type JwtBlacklists internal.JwtBlacklists

// Fill with you ideas below.