// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// MenusParameters is the golang structure for table menus_parameters.
type MenusParameters internal.MenusParameters

// Fill with you ideas below.