// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// MenuParameter is the golang structure for table menu_parameter.
type MenuParameter internal.MenuParameter

// Fill with you ideas below.