// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// OperationRecord is the golang structure for table operation_record.
type OperationRecord internal.OperationRecord

// Fill with you ideas below.