// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// SimpleUploader is the golang structure for table simple_uploader.
type SimpleUploader internal.SimpleUploader

// Fill with you ideas below.