// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// WorkflowMoves is the golang structure for table workflow_moves.
type WorkflowMoves internal.WorkflowMoves

// Fill with you ideas below.