// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// WorkflowNodes is the golang structure for table workflow_nodes.
type WorkflowNodes internal.WorkflowNodes

// Fill with you ideas below.