// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// WorkflowEdges is the golang structure for table workflow_edges.
type WorkflowEdges internal.WorkflowEdges

// Fill with you ideas below.