// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// WorkflowStartPoints is the golang structure for table workflow_start_points.
type WorkflowStartPoints internal.WorkflowStartPoints

// Fill with you ideas below.