// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// WorkflowProcesses is the golang structure for table workflow_processes.
type WorkflowProcesses internal.WorkflowProcesses

// Fill with you ideas below.