// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-app/app/model/internal"
)

// WorkflowEndPoints is the golang structure for table workflow_end_points.
type WorkflowEndPoints internal.WorkflowEndPoints

// Fill with you ideas below.