// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Apis is the golang structure for table apis.
type Apis struct {
    Id          uint64      `orm:"id,primary"  json:"id"`          //              
    CreatedAt   *gtime.Time `orm:"created_at"  json:"createdAt"`   //              
    UpdatedAt   *gtime.Time `orm:"updated_at"  json:"updatedAt"`   //              
    DeletedAt   *gtime.Time `orm:"deleted_at"  json:"deletedAt"`   //              
    Path        string      `orm:"path"        json:"path"`        // api路径      
    Method      string      `orm:"method"      json:"method"`      //              
    ApiGroup    string      `orm:"api_group"   json:"apiGroup"`    // api组        
    Description string      `orm:"description" json:"description"` // api中文描述  
}