// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// BreakpointContinueChunks is the golang structure for table breakpoint_continue_chunks.
type BreakpointContinueChunks struct {
    Id              uint64      `orm:"id,primary"        json:"id"`              //   
    CreatedAt       *gtime.Time `orm:"created_at"        json:"createdAt"`       //   
    UpdatedAt       *gtime.Time `orm:"updated_at"        json:"updatedAt"`       //   
    DeletedAt       *gtime.Time `orm:"deleted_at"        json:"deletedAt"`       //   
    FileChunkPath   string      `orm:"file_chunk_path"   json:"fileChunkPath"`   //   
    FileId          uint64      `orm:"file_id"           json:"fileId"`          //   
    FileChunkNumber int64       `orm:"file_chunk_number" json:"fileChunkNumber"` //   
}