// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// DataAuthorities is the golang structure for table data_authorities.
type DataAuthorities struct {
    AuthorityId   string `orm:"authority_id,primary"   json:"authorityId"`   // 角色ID  
    DataAuthority string `orm:"data_authority,primary" json:"dataAuthority"` // 角色ID  
}