// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Dictionaries is the golang structure for table dictionaries.
type Dictionaries struct {
    Id        uint64      `orm:"id,primary" json:"id"`        //               
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //               
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //               
    DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //               
    Name      string      `orm:"name"       json:"name"`      // 字典名（中）  
    Type      string      `orm:"type"       json:"type"`      // 字典名（英）  
    Status    int         `orm:"status"     json:"status"`    // 状态          
    Desc      string      `orm:"desc"       json:"desc"`      // 描述          
}