// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// DictionaryDetails is the golang structure for table dictionary_details.
type DictionaryDetails struct {
    Id           uint64      `orm:"id,primary"    json:"id"`           //           
    CreatedAt    *gtime.Time `orm:"created_at"    json:"createdAt"`    //           
    UpdatedAt    *gtime.Time `orm:"updated_at"    json:"updatedAt"`    //           
    DeletedAt    *gtime.Time `orm:"deleted_at"    json:"deletedAt"`    //           
    Label        string      `orm:"label"         json:"label"`        // 展示值    
    Status       int         `orm:"status"        json:"status"`       // 启用状态  
    Value        int64       `orm:"value"         json:"value"`        // 字典值    
    Sort         int64       `orm:"sort"          json:"sort"`         // 排序标记  
    DictionaryId uint64      `orm:"dictionary_id" json:"dictionaryId"` // 关联标记  
}