// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// JwtBlacklists is the golang structure for table jwt_blacklists.
type JwtBlacklists struct {
    Id        uint64      `orm:"id,primary" json:"id"`        //      
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //      
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //      
    DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //      
    Jwt       string      `orm:"jwt"        json:"jwt"`       // jwt  
}