// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// MenusParameters is the golang structure for table menus_parameters.
type MenusParameters struct {
    MenuId      uint64 `orm:"menu_id,primary"      json:"menuId"`      //           
    ParameterId uint64 `orm:"parameter_id,primary" json:"parameterId"` // menu的id  
}