// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Menus is the golang structure for table menus.
type Menus struct {
    Id          uint64      `orm:"id,primary"   json:"id"`          //                   
    CreatedAt   *gtime.Time `orm:"created_at"   json:"createdAt"`   //                   
    UpdatedAt   *gtime.Time `orm:"updated_at"   json:"updatedAt"`   //                   
    DeletedAt   *gtime.Time `orm:"deleted_at"   json:"deletedAt"`   //                   
    Path        string      `orm:"path"         json:"path"`        // 路由path          
    Name        string      `orm:"name"         json:"name"`        // 路由name          
    ParentId    string      `orm:"parent_id"    json:"parentId"`    // 父菜单ID          
    Component   string      `orm:"component"    json:"component"`   // 对应前端文件路径  
    Sort        int64       `orm:"sort"         json:"sort"`        // 排序标记          
    MenuLevel   uint64      `orm:"menu_level"   json:"menuLevel"`   //                   
    Hidden      int         `orm:"hidden"       json:"hidden"`      // 是否在列表隐藏    
    KeepAlive   int         `orm:"keep_alive"   json:"keepAlive"`   // 附加属性          
    DefaultMenu int         `orm:"default_menu" json:"defaultMenu"` // 附加属性          
    Icon        string      `orm:"icon"         json:"icon"`        // 附加属性          
    Title       string      `orm:"title"        json:"title"`       // 附加属性          
}