// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// MenuParameter is the golang structure for table menu_parameter.
type MenuParameter struct {
    Id        uint64      `orm:"id,primary" json:"id"`        //                                  
    CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //                                  
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //                                  
    DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //                                  
    Key       string      `orm:"key"        json:"key"`       // 地址栏携带参数的key              
    Type      string      `orm:"type"       json:"type"`      // 地址栏携带参数为params还是query  
    Value     string      `orm:"value"      json:"value"`     // 地址栏携带参数的值               
    MenuId    uint64      `orm:"menu_id"    json:"menuId"`    // menu的id                         
}