// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// OperationRecord is the golang structure for table operation_record.
type OperationRecord struct {
    Id           uint64      `orm:"id,primary"    json:"id"`           //           
    CreatedAt    *gtime.Time `orm:"created_at"    json:"createdAt"`    //           
    UpdatedAt    *gtime.Time `orm:"updated_at"    json:"updatedAt"`    //           
    DeletedAt    *gtime.Time `orm:"deleted_at"    json:"deletedAt"`    //           
    Ip           string      `orm:"ip"            json:"ip"`           // 请求ip    
    Path         string      `orm:"path"          json:"path"`         // 请求路径  
    Agent        string      `orm:"agent"         json:"agent"`        // 代理      
    Method       string      `orm:"method"        json:"method"`       // 请求方法  
    Body         string      `orm:"body"          json:"body"`         // 请求Body  
    Resp         string      `orm:"resp"          json:"resp"`         // 响应Body  
    ErrorMessage string      `orm:"error_message" json:"errorMessage"` // 错误信息  
    Status       int64       `orm:"status"        json:"status"`       // 请求状态  
    UserId       int64       `orm:"user_id"       json:"userId"`       // 用户id    
    Latency      int64       `orm:"latency"       json:"latency"`      // 延迟      
}