// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// SimpleUploader is the golang structure for table simple_uploader.
type SimpleUploader struct {
    Filename         string `orm:"filename"           json:"filename"`         // 文件名           
    FilePath         string `orm:"file_path"          json:"filePath"`         // 文件本地路径     
    TotalSize        string `orm:"total_size"         json:"totalSize"`        // 总容量           
    Identifier       string `orm:"identifier"         json:"identifier"`       // 文件标识（md5）  
    ChunkNumber      string `orm:"chunk_number"       json:"chunkNumber"`      // 当前切片标记     
    TotalChunks      string `orm:"total_chunks"       json:"totalChunks"`      // 切片总数         
    CurrentChunkPath string `orm:"current_chunk_path" json:"currentChunkPath"` // 切片本地路径     
    CurrentChunkSize string `orm:"current_chunk_size" json:"currentChunkSize"` // 当前切片容量     
    IsDone           int    `orm:"is_done"            json:"isDone"`           // 是否上传完成     
}