// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// WorkflowStartPoints is the golang structure for table workflow_start_points.
type WorkflowStartPoints struct {
    Id             uint64      `orm:"id,primary"       json:"id"`             //   
    CreatedAt      *gtime.Time `orm:"created_at"       json:"createdAt"`      //   
    UpdatedAt      *gtime.Time `orm:"updated_at"       json:"updatedAt"`      //   
    DeletedAt      *gtime.Time `orm:"deleted_at"       json:"deletedAt"`      //   
    X              float64     `orm:"x"                json:"x"`              //   
    Y              float64     `orm:"y"                json:"y"`              //   
    Index          int64       `orm:"index"            json:"index"`          //   
    WorkflowEdgeId string      `orm:"workflow_edge_id" json:"workflowEdgeId"` //   
}