// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// WorkflowMoves is the golang structure for table workflow_moves.
type WorkflowMoves struct {
    Id                uint64      `orm:"id,primary"          json:"id"`                //                 
    CreatedAt         *gtime.Time `orm:"created_at"          json:"createdAt"`         //                 
    UpdatedAt         *gtime.Time `orm:"updated_at"          json:"updatedAt"`         //                 
    DeletedAt         *gtime.Time `orm:"deleted_at"          json:"deletedAt"`         //                 
    WorkflowProcessId string      `orm:"workflow_process_id" json:"workflowProcessId"` // 工作流模板ID    
    WorkflowNodeId    string      `orm:"workflow_node_id"    json:"workflowNodeId"`    // 工作流节点ID    
    BusinessType      string      `orm:"business_type"       json:"businessType"`      // 业务标记        
    BusinessId        uint64      `orm:"business_id"         json:"businessId"`        // 业务ID          
    PromoterId        int64       `orm:"promoter_id"         json:"promoterId"`        // 当前流转发起人  
    OperatorId        int64       `orm:"operator_id"         json:"operatorId"`        // 当前流转操作人  
    Action            string      `orm:"action"              json:"action"`            // 工作流驱动事件  
    Param             string      `orm:"param"               json:"param"`             // 工作流驱动参数  
    IsActive          int         `orm:"is_active"           json:"isActive"`          // 是否是活跃节点  
}