// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// WorkflowNodes is the golang structure for table workflow_nodes.
type WorkflowNodes struct {
    Id                string      `orm:"id,primary"          json:"id"`                // 节点id        
    CreatedAt         *gtime.Time `orm:"created_at"          json:"createdAt"`         //               
    UpdatedAt         *gtime.Time `orm:"updated_at"          json:"updatedAt"`         //               
    DeletedAt         *gtime.Time `orm:"deleted_at"          json:"deletedAt"`         //               
    WorkflowProcessId string      `orm:"workflow_process_id" json:"workflowProcessId"` // 流程标识      
    Clazz             string      `orm:"clazz"               json:"clazz"`             // 节点类型      
    Label             string      `orm:"label"               json:"label"`             // 节点名称      
    Type              string      `orm:"type"                json:"type"`              // 图标类型      
    Shape             string      `orm:"shape"               json:"shape"`             // 形状          
    Description       string      `orm:"description"         json:"description"`       // 详细介绍      
    View              string      `orm:"view"                json:"view"`              // 前端视图文件  
    X                 float64     `orm:"x"                   json:"x"`                 // x位置         
    Y                 float64     `orm:"y"                   json:"y"`                 // y位置         
    WaitState         string      `orm:"wait_state"          json:"waitState"`         // 等待属性      
    StateValue        string      `orm:"state_value"         json:"stateValue"`        // 等待值        
    To                string      `orm:"to"                  json:"to"`                // 收件人        
    Subject           string      `orm:"subject"             json:"subject"`           // 标题          
    Content           string      `orm:"content"             json:"content"`           // 内容          
    Cycle             string      `orm:"cycle"               json:"cycle"`             // 循环时间      
    Duration          string      `orm:"duration"            json:"duration"`          // 持续时间      
    HideIcon          int         `orm:"hide_icon"           json:"hideIcon"`          // 是否隐藏图标  
    DueDate           *gtime.Time `orm:"due_date"            json:"dueDate"`           // 到期时间      
    AssignType        string      `orm:"assign_type"         json:"assignType"`        // 审批类型      
    AssignValue       string      `orm:"assign_value"        json:"assignValue"`       // 审批类型值    
    Success           int         `orm:"success"             json:"success"`           // 是否成功      
}