// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// WorkflowProcesses is the golang structure for table workflow_processes.
type WorkflowProcesses struct {
    Id          string      `orm:"id,primary"  json:"id"`          // 流程标识      
    CreatedAt   *gtime.Time `orm:"created_at"  json:"createdAt"`   //               
    UpdatedAt   *gtime.Time `orm:"updated_at"  json:"updatedAt"`   //               
    DeletedAt   *gtime.Time `orm:"deleted_at"  json:"deletedAt"`   //               
    Name        string      `orm:"name"        json:"name"`        // 流程名称      
    Category    string      `orm:"category"    json:"category"`    // 分类          
    Clazz       string      `orm:"clazz"       json:"clazz"`       // 类型          
    Label       string      `orm:"label"       json:"label"`       // 流程标题      
    HideIcon    int         `orm:"hide_icon"   json:"hideIcon"`    // 是否隐藏图标  
    Description string      `orm:"description" json:"description"` // 详细介绍      
    View        string      `orm:"view"        json:"view"`        // 前端视图文件  
}