// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// apisDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type apisDao struct {
	*internal.ApisDao
}

var (
	// Apis is globally public accessible object for table apis operations.
	Apis = &apisDao{
		internal.Apis,
	}
)

// Fill with you ideas below.