// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// breakpointContinueChunksDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type breakpointContinueChunksDao struct {
	*internal.BreakpointContinueChunksDao
}

var (
	// BreakpointContinueChunks is globally public accessible object for table breakpoint_continue_chunks operations.
	BreakpointContinueChunks = &breakpointContinueChunksDao{
		internal.BreakpointContinueChunks,
	}
)

// Fill with you ideas below.