// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// breakpointContinueDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type breakpointContinueDao struct {
	*internal.BreakpointContinueDao
}

var (
	// BreakpointContinue is globally public accessible object for table breakpoint_continue operations.
	BreakpointContinue = &breakpointContinueDao{
		internal.BreakpointContinue,
	}
)

// Fill with you ideas below.