// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// menuParameterDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type menuParameterDao struct {
	*internal.MenuParameterDao
}

var (
	// MenuParameter is globally public accessible object for table menu_parameter operations.
	MenuParameter = &menuParameterDao{
		internal.MenuParameter,
	}
)

// Fill with you ideas below.