// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// menusDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type menusDao struct {
	*internal.MenusDao
}

var (
	// Menus is globally public accessible object for table menus operations.
	Menus = &menusDao{
		internal.Menus,
	}
)

// Fill with you ideas below.