// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// operationRecordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type operationRecordDao struct {
	*internal.OperationRecordDao
}

var (
	// OperationRecord is globally public accessible object for table operation_record operations.
	OperationRecord = &operationRecordDao{
		internal.OperationRecord,
	}
)

// Fill with you ideas below.