// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// simpleUploaderDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type simpleUploaderDao struct {
	*internal.SimpleUploaderDao
}

var (
	// SimpleUploader is globally public accessible object for table simple_uploader operations.
	SimpleUploader = &simpleUploaderDao{
		internal.SimpleUploader,
	}
)

// Fill with you ideas below.