// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// workflowMovesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type workflowMovesDao struct {
	*internal.WorkflowMovesDao
}

var (
	// WorkflowMoves is globally public accessible object for table workflow_moves operations.
	WorkflowMoves = &workflowMovesDao{
		internal.WorkflowMoves,
	}
)

// Fill with you ideas below.