// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// workflowEdgesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type workflowEdgesDao struct {
	*internal.WorkflowEdgesDao
}

var (
	// WorkflowEdges is globally public accessible object for table workflow_edges operations.
	WorkflowEdges = &workflowEdgesDao{
		internal.WorkflowEdges,
	}
)

// Fill with you ideas below.