// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// workflowEndPointsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type workflowEndPointsDao struct {
	*internal.WorkflowEndPointsDao
}

var (
	// WorkflowEndPoints is globally public accessible object for table workflow_end_points operations.
	WorkflowEndPoints = &workflowEndPointsDao{
		internal.WorkflowEndPoints,
	}
)

// Fill with you ideas below.