// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-app/app/dao/internal"
)

// workflowStartPointsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type workflowStartPointsDao struct {
	*internal.WorkflowStartPointsDao
}

var (
	// WorkflowStartPoints is globally public accessible object for table workflow_start_points operations.
	WorkflowStartPoints = &workflowStartPointsDao{
		internal.WorkflowStartPoints,
	}
)

// Fill with you ideas below.